version: '3'
services:
  rabbit1:
    image: rabbitmq:3-management
    container_name: rabbit1
    hostname: rabbit1
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE=shared_cookie
    volumes:
      - ./rabbit1-definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  rabbit2:
    image: rabbitmq:3-management
    container_name: rabbit2
    hostname: rabbit2
    command: sh -c 'sleep 10 && rabbitmq-server'
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE=shared_cookie
    volumes:
      - ./rabbit2-definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro